import type { Metadata } from "next";
import './global.scss';
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import Header from "./components/header/header";
import Image from "next/image";
import {Telegram, Logo, Vk, Youtube} from "../../img"

const paluiBold = localFont({
  src: "./fonts/PaluiSPDemo-Bold.otf",
  variable: "--font-palui", 
  weight: "700",             
  style: "normal"
});
export const visbyRegular = localFont({
  src: "./fonts/VisbyRegular.otf",
  variable: "--font-visby-regular",
  weight: "400",
  style: "normal",
});
export const visbySemibold = localFont({
  src: "./fonts/VisbySemibold.otf",
  variable: "--font-visby-semibold",
  weight: "600",
  style: "normal",
});
export const visbyBold = localFont({
  src: "./fonts/VisbyBold.otf",
  variable: "--font-visby-bold",
  weight: "700",
  style: "normal",
});

export const metadata: Metadata = {
  title: "Челбаскет",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ru" className={`
      ${visbyRegular.variable}
      ${visbySemibold.variable}
      ${visbyBold.variable}
      ${paluiBold.variable}
    `}>
      <body>
        <Header />
        <main>{children}</main>
      </body>
      <footer>
          <div className="normalization-of-position">
            <div className="left-content">
              <Image src={Logo} alt="logo" width={200}></Image>
              <p className="label-text">Станьте тем, кто первый узнает об обновлениях в коллекциях</p>
              <input className="E-mail" type="text" placeholder="E-mail" required/>
              <p className="opacity-text">Указывая E-mail вы соглашаетесь на рассылку</p>
              <button className="button_enter_footer">Подписаться</button>
            </div>
            <div className="right-content">
              <ul>
                <li>Футболки</li>
                <li>Майки</li>
                <li>Кофты</li>
                <li>Мячи</li>
                <li>Сувениры</li>
              </ul>
            </div>
          </div>
          <div className="under-element">
            <div className="element_under_center">
              <p>2025</p>
              <p>Политика конфиденциальности</p>
              <div className="img_footer">
                <Image src={Vk} alt="telegram" width={25}></Image>
                <Image src={Youtube} alt="telegram" width={25}></Image>
                <Image src={Telegram} alt="telegram" width={25}></Image>
              </div>
            </div>
          </div>
       </footer>
    </html>
  );
}
