
import type { Metadata } from "next";
import './global.scss';
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import Header from "./components/header/header";

const paluiBold = localFont({
  src: "./fonts/PaluiSPDemo-Bold.otf",
  variable: "--font-palui", 
  weight: "700",             
  style: "normal"
});
export const visbyRegular = localFont({
  src: "./fonts/VisbyRegular.otf",
  variable: "--font-visby-regular",
  weight: "400",
  style: "normal",
});
export const visbySemibold = localFont({
  src: "./fonts/VisbySemibold.otf",
  variable: "--font-visby-semibold",
  weight: "600",
  style: "normal",
});
export const visbyBold = localFont({
  src: "./fonts/VisbyBold.otf",
  variable: "--font-visby-bold",
  weight: "700",
  style: "normal",
});

export const metadata: Metadata = {
  title: "Челбаскет",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ru" className={`
      ${visbyRegular.variable}
      ${visbySemibold.variable}
      ${visbyBold.variable}
      ${paluiBold.variable}
    `}>
      <body>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
